### ISSUE TITLE
make log dir configurable

### ISSUE THREAD

**Issue by balmas** [PerseusDL/imgup#4]
rake redis reports an error on a missing log file:

/usr/local/imgcollect/rails3/log/redis.log

This location should probably be configurable

**Comment by balmas** [comment]
also, same for sidekiq:
ubuntu@www:/usr/local/imgup$ No such file or directory @ rb_sysopen - log/sidekiq.log

**Comment by caesarfeta** [comment]
https://github.com/PerseusDL/imgup/pull/14
